---
.asdf:
  type: 'git-repo'
  url: 'https://github.com/asdf-vm/asdf.git'

.local/bin:
  type: 'archive'
  url: '{{ replace "/releases/tag/" "/releases/download/" (gitHubLatestRelease "stuartleeks/devcontainer-cli").HTMLURL }}/devcontainer-cli_linux_amd64.tar.gz'
  include: ['devcontainer']

.shell/modules/bash-aptfile:
  type: 'git-repo'
  url: 'https://github.com/seatgeek/bash-aptfile.git'
  refreshPeriod: '168h'

.shell/modules/bat-extras:
  type: 'git-repo'
  url: 'https://github.com/eth-p/bat-extras.git'
  refreshPeriod: '168h'

.vim/bundle/Vundle.vim:
  type: 'git-repo'
  url: 'https://github.com/VundleVim/Vundle.vim.git'
  refreshPeriod: '168h'
