---
.asdf:
  type: 'git-repo'
  url: 'https://github.com/asdf-vm/asdf.git'

.local/bin/aptfile:
  type: 'file'
  url: '{{ (gitHubLatestRelease "seatgeek/bash-aptfile").TarballURL }}'
  executable: true
  filter:
    command: 'tar'
    args: ['--extract', '--to-stdout', '--file=-', '--gzip', '--wildcards', '*/bin/aptfile']

.local/bin/atlas:
  type: 'file'
  url: 'https://statlas.prod.atl-paas.net/atlas-cli/{{ .chezmoi.os }}/atlas-latest-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz'
  executable: true
  filter:
    command: 'tar'
    args: ['--extract', '--to-stdout', '--file=-', '--gzip', 'atlas']
  refreshPeriod: '24h'

.local/bin/cloudtoken:
  type: 'file'
  url: 'https://statlas.prod.atl-paas.net/cloudtoken/cloudtoken-{{ .chezmoi.os }}-{{ .chezmoi.arch }}-latest.zip'
  executable: true
  filter:
    command: 'bsdtar'
    args: ['--extract', '--file=-', '--to-stdout', 'cloudtoken']
  refreshPeriod: '24h'

.local/bin/devcontainer:
  type: 'file'
  url: '{{ replace "/releases/tag/" "/releases/download/" (gitHubLatestRelease "stuartleeks/devcontainer-cli").HTMLURL }}/devcontainer-cli_{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz'
  executable: true
  filter:
    command: 'tar'
    args: ['--extract', '--to-stdout', '--file=-', '--gzip', 'devcontainer']

.vim/autoload/plug.vim:
  type: 'file'
  url: '{{ (gitHubLatestRelease "junegunn/vim-plug").TarballURL }}'
  filter:
    command: 'tar'
    args: ['--extract', '--to-stdout', '--file=-', '--gzip', '--wildcards', '*/plug.vim']
