---
.asdf:
  type: 'git-repo'
  url: 'https://github.com/asdf-vm/asdf.git'

.local/bin/devcontainer:
  type: 'file'
  url: '{{ replace "/releases/tag/" "/releases/download/" (gitHubLatestRelease "stuartleeks/devcontainer-cli").HTMLURL }}/devcontainer-cli_{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz'
  executable: true
  filter:
    command: 'tar'
    args: ['--extract', '--file', '/dev/stdin', '--gzip', '--to-stdout', 'devcontainer']

.local/bin/hub-tool:
  type: 'file'
  url: '{{ replace "/releases/tag/" "/releases/download/" (gitHubLatestRelease "docker/hub-tool").HTMLURL }}/hub-tool-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz'
  executable: true
  filter:
    command: 'tar'
    args: ['--extract', '--file', '/dev/stdin', '--gzip', '--to-stdout', 'hub-tool/hub-tool']

.local/bin/aptfile:
  type: 'file'
  url: 'https://github.com/seatgeek/bash-aptfile/archive/refs/tags/1.2.0.tar.gz'
  executable: true
  filter:
    command: 'tar'
    args: ['--extract', '--file', '/dev/stdin', '--gzip', '--to-stdout', '--wildcards', 'bash-aptfile-*/bin/aptfile']

.shell/modules/bat-extras:
  type: 'git-repo'
  url: 'https://github.com/eth-p/bat-extras.git'
  refreshPeriod: '168h'

.vim/bundle/Vundle.vim:
  type: 'git-repo'
  url: 'https://github.com/VundleVim/Vundle.vim.git'
  refreshPeriod: '168h'
