---
language: 'shell'
os: 'ubuntu'

before_install:
  - 'sudo pip install --quiet dotfiles'
install:
  - 'dotfiles --repo home --config home/dotfilesrc --sync'
  - 'ls -al ~'
script:
  # Validate SSH configuration
  - 'ssh -G localhost >/dev/null'
