---
git:
  quiet: true
language: 'shell'
os: 'ubuntu'
services:
  - 'docker'

before_install:
  - 'sudo pip install --quiet dotfiles'
install:
  - 'make install-virtualenv'
script:
  - 'make compile'
  - 'make lint'
  - 'make test'
