---
language: 'shell'
os: 'ubuntu'
services:
  - 'docker'

before_install:
  - 'sudo pip install --quiet dotfiles'
install:
  - 'dotfiles --repo home --config home/dotfilesrc --home /tmp/home --sync'
script:
  - 'make test'
