---
# yamllint disable rule:key-ordering
language: 'shell'
os: 'ubuntu'
services:
  - 'docker'

install:
  - 'sudo apt update'
  - 'sudo apt install python3 python3-virtualenv'
script:
  - 'make compile'
  - 'make lint'
  - 'make test'
