#!/bin/bash

# Skip this config if we aren't in bash.
[ -n $BASH_VERSION ] || return

# Skip the rest if this is not an interactive shell.
if [[ -z $PS1 && "$-" != "*i*" ]]; then return; fi

source ${HOME}/.shell/functions/source

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    source_r /etc/bash_completion
fi

# We run the environment settings for all shells to ensure it's always set up.
source_r $HOME/.shell/environment

# An interactive shell starting bashrc is not a login shell, just run
# interactive setup.
if [ -n $PS1 ]; then
    source_r $HOME/.shell/interactive
fi

source_r $HOME/.shell/functions

bash_prompt