#!/bin/bash

# We need the sh_source_r function!
source "$HOME/.shell/functions/source/sh_source_r"

# We run the environment settings for all shells to ensure it's always set up.
sh_source_r "$HOME/.shell/environment"

# Set up command aliases.
sh_source_r "$HOME/.shell/aliases"

# Import user-defined functions.
sh_source_r "$HOME/.shell/functions"

# If PS1 is defined then the shell should be interactive.
if [ -n "$PS1" ]; then
    [ -f "$HOME/.shell/completion.bash" ] && source "$HOME/.shell/completion.bash"
fi
