#!/bin/sh

# When leaving the console clear the screen to increase privacy. This first
# checks that shell level is equal to 1.
if [ $SHLVL = 1 ]; then
    command -v clear_console && command clear_console -q
fi
