"/
"" Vanilla configuration for {@link http://www.vim.org/ vim}.
""
"" @author Joshua Spence
"" @file   ~/.vimrc
"\

"" General "{{{
  "" Walk directory tree up to $HOME looking for tags.
  set tags=./tags;$HOME

  "" Modeline "{{{
    set modeline

    "" Default numbers of lines to read for modeline instructions.
    set modelines=5
  "" "}}}

  "" Backup "{{{
    "" prepend(^=) $HOME/.tmp/ to default path. Use full path as backup filename(//).
    set directory=/tmp//
  "" "}}}
"" "}}}

"" Visual "{{{
  "" Format options "{{{
    "" Support for numbered/bullet lists.
    set formatoptions+=n

    "" Automatically insert the current comment leader after hitting 'o' or 'O'
    "" in Normal mode.
    set formatoptions+=o
  
    "" Do not automatically insert a comment leader after an enter.
    set formatoptions-=r

    "" Do not auto-wrap text using textwidth (does not apply to comments).
    set formatoptions-=t
  "" "}}}

  "" Commands "{{{
    " Display an incomplete command in the lower right corner of the vim window.
    set showcmd

    "" Make the command area two lines high.
    set cmdheight=2
  "" "}}}

  "" Sounds "{{{
    "" No noise.
    set noerrorbells

    "" No blinking.
    set novisualbell

    "" @todo
    set t_vb=
  "" "}}}

  "" Shortens messages "{{{
    set shortmess=

    set shortmess+=a

    set shortmess+=t

    set shortmess+=I

    set shortmess+=o
  "" "}}}
"" "}}}

"" Functionality "{{{
  "" Automatically detect file types.
  filetype plugin indent on

  "" "{{{
    "" Display unprintable characters (<F12> switches).
    set nolist

    "" Unprintable chars mapping
    set listchars=tab:·\ ,eol:¶,trail:·,extends:»,precedes:«
  "" "}}}
"" "}}}

"" Spelling "{{{
  "" Set the dictionary.
  set dictionary=/usr/share/dict/words

  if v:version >= 700
    setlocal spell spelllang=en
    nmap ,ll :set spell!</cr><cr>
    nmap ,le :set spelllang=en</cr><cr>
    nmap ,lp :set spelllang=pt</cr><cr>
  endif

  "" Correct some spelling mistakes. "{{{
    ia teh      the
    ia htis     this
    ia tihs     this
    ia funciton function
    ia fucntion function
    ia funtion  function
    ia retunr   return
    ia reutrn   return
    ia sefl     self
    ia eslf     self
  "" "}}}
"" "}}}

"" Advanced "{{{
  "" Buffers "{{{
    "" The current buffer can be put to the background without writing to disk.
    set hidden
  "" "}}}
"" "}}}

"" "{{{
  if has("autocmd")
      source ~/.vim/filetype.vim
  endif
  source ~/.vim/mappings.vim
"" "}}}
