set nocompatible
filetype off

" Initialize Vundle.
set runtimepath+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Let Vundle manage Vundle.
Plugin 'VundleVim/Vundle.vim', {'pinned': 1}

" Plugins.
Plugin 'vim-syntastic/syntastic'
Plugin 'myint/syntastic-extras'
Plugin 'sickill/vim-monokai'
Plugin 'matze/vim-move'
Plugin 'tpope/vim-sensible'
Plugin 'Valloric/YouCompleteMe'

" TODO: Automatically install plugins.
" See https://github.com/VundleVim/Vundle.vim/issues/414.

" TODO: Compile `ycmd`.
" See https://github.com/Valloric/YouCompleteMe.

call vundle#end()
filetype plugin indent on
