#!/bin/sh

# Check if this is an SSH connection.
source "$HOME/.shell/environment/ssh"

if [ -z $IS_SSH ] && command -v google-chrome; then
    BROWSER=google-chrome
elif [ -z $IS_SSH ] && command -v firefox; then
    BROWSER=firefox
elif command -v lynx; then
    BROWSER=lynx
else
    echo "No command set for BROWSER environment variable" >&2
fi
export BROWSER
