#!/bin/sh

export BLACK='\[\033[0;30m\]'
export RED='\[\033[0;31m\]'
export GREEN='\[\033[0;32m\]'
export BROWN='\[\033[0;33m\]'
export BLUE='\[\033[0;34m\]'
export PURPLE='\[\033[0;35m\]'
export CYAN='\[\033[0;36m\]'
export LIGHTGRAY='\[\033[0;37m\]'

export DARKGRAY='\[\033[1;30m\]'
export LIGHTRED='\[\033[1;31m\]'
export LIGHTGREEN='\[\033[1;32m\]'
export YELLOW='\[\033[1;33m\]'
export LIGHTBLUE='\[\033[1;34m\]'
export LIGHTPURPLE='\[\033[1;35m\]'
export LIGHTCYAN='\[\033[1;36m\]'
export WHITE='\[\033[1;37m\]'

export BLACK_UNDERLINE='\[\033[4;30m\]'
export RED_UNDERLINE='\[\033[4;31m\]'
export GREEN_UNDERLINE='\[\033[4;32m\]'
export YELLOW_UNDERLINE='\[\033[4;33m\]'
export BLUE_UNDERLINE='\[\033[4;34m\]'
export PURPLE_UNDERLINE='\[\033[4;35m\]'
export CYAN_UNDERLINE='\[\033[4;36m\]'
export WHITE_UNDERLINE='\[\033[4;37m\]'

export BLACK_BACKGROUND='\[\033[40m\]'
export RED_BACKGROUND='\[\033[41m\]'
export GREEN_BACKGROUND='\[\033[42m\]'
export YELLOW_BACKGROUND='\[\033[43m\]'
export BLUE_BACKGROUND='\[\033[44m\]'
export PURPLE_BACKGROUND='\[\033[45m\]'
export CYAN_BACKGROUND='\[\033[46m\]'
export WHITE_BACKGROUND='\[\033[47m\]'

export NO_COLOR='\[\033[0m\]'
export NC=$NO_COLOR

# Terminals that we want coloured prompts in
if [[ -n ${COLORTERM} || $(tput colors) -gt 2 ]]; then
    PS1_COLOR=1
fi
