#!/bin/bash

# Check if this is an SSH connection.
source "$HOME/.shell/environment/ssh"

if [ -z $IS_SSH ] && command -v subl; then
    EDITOR=subl
elif [ -z $IS_SSH ] && command -v sublime-text-2; then
    EDITOR=sublime-text-2
elif command -v vim; then
    EDITOR=vim
else
    echo "Unable to set EDITOR environment variable" >&2
fi
export EDITOR

# The `less` pager supports editing the file being viewed by pressing "v".
export LESSEDIT=$EDITOR

# "VISUAL" is basically the same as "EDITOR".
export VISUAL=$EDITOR
