#!/bin/sh

# We need the path functions!
source $HOME/.shell/functions/path

# ~/bin should be in the front of PATH if it exists.
push_path PATH $HOME/bin

# ~/man should be in the front of MANPATH if it exists.
export MANPATH=$(manpath)
push_path MANPATH ${HOME}/man
