module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.18

replace github.com/bradford-hamilton/dora v0.1.1 => github.com/stuartleeks/dora v0.1.5

require github.com/stuartleeks/devcontainer-cli v0.1.2493445248 // cmd/devcontainer
