set nocompatible

if has('syntax')
  syntax on
endif

set background=dark
set ruler

set backupdir=~/.vim/backup | call mkdir(&backupdir, 'p')
set directory=~/.vim/swap   | call mkdir(&directory, 'p')
set undodir=~/.vim/undo     | call mkdir(&undodir,   'p')
set viewdir=~/.vim/view     | call mkdir(&viewdir,   'p')

if !has('nvim') | set viminfofile=~/.vim/viminfo | endif
