set nocompatible
filetype off

call plug#begin()

Plug 'vim-syntastic/syntastic'
Plug 'myint/syntastic-extras'
Plug 'sickill/vim-monokai'
Plug 'matze/vim-move'
Plug 'tpope/vim-sensible'

call plug#end()

set clipboard^=unnamed,unnamedplus
set smartindent
