[[plugin]]
  name = "shipyard"
  summary = "Manage artifacts stored in Shipyard"
  version = "v2.8.1-3-gbcc3c59"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/shipyard"
  channel = "stable"

[[plugin]]
  name = "slauth"
  summary = "Service Layer Authentication"
  version = "1.0.14"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/slauth"
  channel = "stable"

[[plugin]]
  name = "statlas"
  summary = "Statlas auth and upload cli"
  version = "1.1.4"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/statlas"
  channel = "stable"

[[plugin]]
  name = "micros"
  summary = "Micros plugin for atlas-cli"
  version = "130-ce797f5"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/micros"
  channel = "stable"

[[plugin]]
  name = "kudos"
  summary = "A simple and quick way to thank your fellow Atlassians from the command line."
  version = "3.3.5"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/kudos"
  channel = "stable"

[[plugin]]
  name = "hammertime"
  summary = "The unofficial PerfHammer client."
  version = "0.0.5"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/hammertime"
  channel = "stable"

[[plugin]]
  name = "asap"
  summary = "ASAP Key management, ASAP requests, and token generation & validation"
  version = "1.1.7"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/asap"
  channel = "stable"

[[plugin]]
  name = "share"
  summary = "Plugin to share secrets with other atlassians"
  version = "1.1.2"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/share"
  channel = "stable"

[[plugin]]
  name = "nebulae"
  summary = "Nebulae"
  version = "2.1.0"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/nebulae"
  channel = "stable"

[[plugin]]
  name = "poco"
  summary = "Poco plugin for atlas-cli"
  version = "1.1.30"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/poco"
  channel = "stable"

[[plugin]]
  name = "spin"
  summary = "Plugin for Spinnaker"
  version = "0.8.319-8c65b04"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/spin"
  channel = "stable"

[[plugin]]
  name = "secrets"
  summary = "Plugin for Vault secrets management"
  version = "0.5.0-71-gdbfec814"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/secrets"
  channel = "stable"

[[plugin]]
  name = "packages"
  summary = "Provides a set of tools for working with packages.a.c"
  version = "1.6.42"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/packages"
  channel = "stable"

[[plugin]]
  name = "atlasdev"
  summary = "Plugin for atlas-cli developers"
  version = "0.0-801-g476469d"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/atlasdev"
  channel = "stable"

[[plugin]]
  name = "atlops"
  summary = "Generic composable operations plugin (see go/atlops for more)"
  version = "1.0.34"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/atlops"
  channel = "stable"

[[plugin]]
  name = "chaos"
  summary = "brahmos cli plugin"
  version = "15-8fd8d25"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/chaos"
  channel = "stable"

[[plugin]]
  name = "cprs"
  summary = "Command line interface for the Command Peer Review System."
  version = "1.0.28-stable"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/cprs"
  channel = "stable"

[[plugin]]
  name = "dac"
  summary = "Atlas CLI DAC plugin"
  version = "20973-b01e87215d057dc7e0a1f69655d4f0fc371cfb4c"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/dac"
  channel = "stable"

[[plugin]]
  name = "perfhammer"
  summary = "The official PerfHammer cli client."
  version = "1.6.3"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/perfhammer"
  channel = "stable"

[[plugin]]
  name = "sonar"
  summary = "Atlassian-configured Sonar scans"
  version = "0.1.438"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/sonar"
  channel = "stable"
