[[plugin]]
  name = "shipyard"
  summary = "Manage artifacts stored in Shipyard"
  version = "v2.7.0"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/shipyard"
  channel = "stable"

[[plugin]]
  name = "slauth"
  summary = "Service Layer Authentication"
  version = "0.0-612-gf826748"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/slauth"
  channel = "stable"

[[plugin]]
  name = "statlas"
  summary = "Statlas auth and upload cli"
  version = "build-155-6dc107d"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/statlas"
  channel = "stable"

[[plugin]]
  name = "micros"
  summary = "Micros plugin for atlas-cli"
  version = "153-0d29d63"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/micros"
  channel = "stable"

[[plugin]]
  name = "kudos"
  summary = "A simple and quick way to thank your fellow Atlassians from the command line."
  version = "3.3.2"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/kudos"
  channel = "stable"

[[plugin]]
  name = "hammertime"
  summary = "The unofficial PerfHammer client."
  version = "0.0.4"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/hammertime"
  channel = "stable"

[[plugin]]
  name = "asap"
  summary = "ASAP Key management, ASAP requests, and token generation & validation"
  version = "build-268-b71d0a0"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/asap"
  channel = "stable"

[[plugin]]
  name = "share"
  summary = "Plugin to share secrets with other atlassians"
  version = "80-d538034"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/share"
  channel = "stable"
