[[plugin]]
  name = "shipyard"
  summary = "Manage artifacts stored in Shipyard"
  version = "v2.6.1"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/shipyard"
  channel = "stable"

[[plugin]]
  name = "slauth"
  summary = "Service Layer Authentication"
  version = "0.0-483-gb62bf23"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/slauth"
  channel = "stable"

[[plugin]]
  name = "statlas"
  summary = "Statlas auth and upload cli"
  version = "22-527cccc"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/statlas"
  channel = "stable"

[[plugin]]
  name = "micros"
  summary = "Micros plugin for atlas-cli"
  version = "102-98a2063"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/micros"
  channel = "stable"

[[plugin]]
  name = "kudos"
  summary = "A simple and quick way to thank your fellow Atlassians from the command line."
  version = "1.2.9"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/kudos"
  channel = "stable"
