[[plugin]]
  name = "shipyard"
  summary = "Manage artifacts stored in Shipyard"
  version = "v2.8.0-29-gf958272"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/shipyard"
  channel = "stable"

[[plugin]]
  name = "slauth"
  summary = "Service Layer Authentication"
  version = "1.0.7"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/slauth"
  channel = "stable"

[[plugin]]
  name = "statlas"
  summary = "Statlas auth and upload cli"
  version = "1.1.3"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/statlas"
  channel = "stable"

[[plugin]]
  name = "micros"
  summary = "Micros plugin for atlas-cli"
  version = "272-cc6265b"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/micros"
  channel = "stable"

[[plugin]]
  name = "kudos"
  summary = "A simple and quick way to thank your fellow Atlassians from the command line."
  version = "3.3.5"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/kudos"
  channel = "stable"

[[plugin]]
  name = "hammertime"
  summary = "The unofficial PerfHammer client."
  version = "0.0.5"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/hammertime"
  channel = "stable"

[[plugin]]
  name = "asap"
  summary = "ASAP Key management, ASAP requests, and token generation & validation"
  version = "1.1.1"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/asap"
  channel = "stable"

[[plugin]]
  name = "share"
  summary = "Plugin to share secrets with other atlassians"
  version = "1.1.2"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/share"
  channel = "stable"

[[plugin]]
  name = "nebulae"
  summary = "Nebulae"
  version = "20210312-001657-2381fdf2a"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/nebulae"
  channel = "stable"

[[plugin]]
  name = "poco"
  summary = "Poco plugin for atlas-cli"
  version = "1.1.14"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/poco"
  channel = "stable"

[[plugin]]
  name = "spin"
  summary = "Plugin for Spinnaker"
  version = "0.8.199-7469739"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/spin"
  channel = "stable"

[[plugin]]
  name = "secrets"
  summary = "Plugin for Vault secrets management"
  version = "0.5.0-25-gd1c0868"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/secrets"
  channel = "stable"

[[plugin]]
  name = "packages"
  summary = "Provides a set of tools for working with packages.a.c"
  version = "1.4.7"
  sha256 = ""
  exec = "/home/jspence2/.local/share/atlassian/atlas/plugin/packages"
  channel = "stable"

[[plugin]]
  name = "atlasdev"
  summary = "Plugin for atlas-cli developers"
  version = "0.0-725-ge2b2207"
  sha256 = ""
  exec = "~/.local/share/atlassian/atlas/plugin/atlasdev"
  channel = "stable"
