unless Vagrant.has_plugin?('vagrant-cachier')
  puts 'You should install the `vagrant-cachier` plugin.'
end

unless Vagrant.has_plugin?('vagrant-vbguest')
  puts 'You should install the `vagrant-vbguest` plugin.'
end

Vagrant.configure('2') do |config|
  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.synced_folder_opts = {
      type: :nfs,
    }
  end

  if Vagrant.has_plugin?('vagrant-vbguest')
    config.vbguest.no_install = true
  end
end
