unless Vagrant.has_plugin?('vagrant-aws')
  puts 'You should install the `vagrant-aws` plugin.'
end

unless Vagrant.has_plugin?('vagrant-hostmanager')
  puts 'You should install the `vagrant-hostmanager` plugin.'
end

unless Vagrant.has_plugin?('vagrant-vbguest')
  puts 'You should install the `vagrant-vbguest` plugin.'
end

Vagrant.configure('2') do |config|
  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
      type: :nfs,
    }
  end

  if Vagrant.has_plugin?('vagrant-hostmanager')
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.include_offline = true
  end

  if Vagrant.has_plugin?('vagrant-vbguest')
    config.vbguest.no_install = true
  end
end
