[settings]
idiomatic_version_file_enable_tools = ["go", "node", "pnpm", "python", "terraform", "terragrunt"]
npm.package_manager = "pnpm"

[tools]
amazon-ecr-credential-helper = "latest"
ansible = "latest"
chezmoi = "latest"
"github:docker-credential-magic/docker-credential-magic" = "latest"
golangci-lint = "latest"
grpcurl = "latest"
hadolint = "latest"
k9s = "latest"
markdownlint-cli2 = "latest"
node = "lts"
pre-commit = "latest"
python = "3"
shellcheck = "latest"
shfmt = "latest"
terraform = "latest"
terraform-docs = "latest"
terragrunt = "latest"
tflint = "latest"
yamllint = "latest"
yq = "latest"
