---
name: 'Chezmoi'
description: 'GitHub action for Chezmoi.'
runs:
  using: 'composite'
  steps:
    - name: 'Install Chezmoi'
      shell: 'bash'
      run: 'curl --fail --location --no-progress-meter https://get.chezmoi.io | sh -s -- -b ${{ github.action_path }}'
    - name: 'Add Chezmoi to $PATH'
      shell: 'bash'
      run: 'echo "${{ github.action_path }}" >> $GITHUB_PATH'
    - name: 'Display Chezmoi version'
      shell: 'bash'
      run: 'chezmoi --version'

    - shell: 'bash'
      run: 'chezmoi init .'
