---
defaults:
  idaptive:
    appkey: 'aa23927a-08ea-4530-8fc3-2bd0b311f4ab'
    auth_preferences:
      - 'Password'
      - 'MFA (US-East-1)'
    mfa_method: 'passcode'
    tenant_id: 'AAS0641'
    vanity_id: 'atlassian'
  saml:
    saml_response_plugin: 'idaptive'
  system_username: 'jspence2'
plugins:
  auth:
    - 'idaptive'
    - 'saml'
  post_auth:
    - 'url_generator'
    - 'export_credentials_awscli'
  pre_auth: []
