# https://wiki.archlinux.org/index.php/Bash/Prompt_customization#Common_capabilities
# shellcheck disable=SC2034

COLOR_NONE='\e[0m'

# Normal colors
COLOR_BLACK='\e[0;30m'
COLOR_RED='\e[0;31m'
COLOR_GREEN='\e[0;32m'
COLOR_YELLOW='\e[0;33m'
COLOR_BLUE='\e[0;34m'
COLOR_MAGENTA='\e[0;35m'
COLOR_CYAN='\e[0;36m'
COLOR_WHITE='\e[0;37m'

# Bold colors
BOLDCOLOR_BLACK='\e[1;30m'
BOLDCOLOR_RED='\e[1;31m'
BOLDCOLOR_GREEN='\e[1;32m'
BOLDCOLOR_YELLOW='\e[1;33m'
BOLDCOLOR_BLUE='\e[1;34m'
BOLDCOLOR_MAGENTA='\e[1;35m'
BOLDCOLOR_CYAN='\e[1;36m'
BOLDCOLOR_WHITE='\e[1;37m'

# Backgrounds
BACKGROUND_BLACK='\e[40m'
BACKGROUND_RED='\e[41m'
BACKGROUND_GREEN='\e[42m'
BACKGROUND_YELLOW='\e[43m'
BACKGROUND_BLUE='\e[44m'
BACKGROUND_MAGENTA='\e[45m'
BACKGROUND_CYAN='\e[46m'
BACKGROUND_WHITE='\e[47m'

# Styles
STYLE_PLAIN='\e[0m'
STYLE_BOLD='\e[1m'
STYLE_NOBOLD='\e[22m'
STYLE_DIM='\e[2m'
STYLE_ITALIC='\e[3m'
STYLE_NOITALIC='\e[23m'
STYLE_UNDERLINE='\e[4m'
STYLE_NOUNDERLINE='\e[24m'
STYLE_BLINKING='\e[5m'
STYLE_NOBLINKING='\e[25m'
STYLE_HIGHLIGHT='\e[7m'
STYLE_NOHIGHLIGHT='\e[27m'
STYLE_STRIKETHROUGH='\e[9m'
STYLE_NOSTRIKETHROUGH='\e[29m'
