#!/bin/sh

##
# ROT13 encoder/decoder.
#
# @link https://github.com/mathiasbynens/dotfiles/blob/master/.aliases
#
alias rot13='tr a-zA-Z n-za-mN-ZA-M'

##
# Remove escape characters from a string.
#
# @link http://unix.stackexchange.com/questions/148/colorizing-your-terminal-and-shell-environment
#
alias unescape='sed '\''s/\[^[[0-9;]*[a-zA-Z]//gi'\'''

##
# URL-encode a string.
#
# @link https://github.com/mathiasbynens/dotfiles/blob/master/.aliases
#
alias urlencode='python -c '\''
import sys;
import urllib;
print urllib.quote_plus(sys.argv[1]);'\'''
