#!/bin/sh

##
# Display the processes that are using the most processing resources.
#
# @link @todo
#
alias cpu_hogs='ps -e -o %cpu,pid,ppid,user,cmd |
    awk '\''NR == 1; NR > 1 {print $0 | "sort -nr"}'\'' |
    head'

##
# Display the processes that are using the most memory.
#
# @link @todo
#
alias mem_hogs='ps -e -o %mem,pid,ppid,user,cmd |
    awk '\''NR == 1; NR > 1 {print $0 | "sort -nr"}'\'' |
    head'

##
# Displays the largest files/directories in the current directory.
#
# @link @todo
#
alias biggest='du -hsk $(ls -A) | sort -rn | head -10'

##
# Recursively displays the largest files/directories in the current directory.
#
# @link @todo
#
alias rbiggest='BLOCKSIZE=1048576; du -hx | sort -nr | head -10'
