#!/bin/sh

##
# Outputs random hexadecimal stuff that makes the screen look busy.
#
# @link @todo
#
alias compute="cat /dev/urandom | hexdump -C | grep --color=auto 'ca fe'"

##
# Cool "The Matrix" type screens.
#
alias matrix=matrix1

##
# Cool "The Matrix" type screens.
#
# @link @todo
#
alias matrix1='(echo -e "\e[32m"
    while true; do
        for i in $(seq 1 $(($(tput cols)/5))); do
            r=$(($RANDOM % 2))
            if [ $(($RANDOM % 5)) == 1 ]; then
                if [ $(($RANDOM % 4)) == 1 ]; then
                    v+="\e[1m $r   "
                else
                    v+="\e[2m $r   "
                fi
            else
                v+="     "
            fi
        done
        echo -e "$v"
        unset i
        unset v
    done)'

##
# Cool "The Matrix" type screens.
#
# @link @todo
#
alias matrix2='(echo -ne "\e[32m"
    while true; do
        echo -ne "\e[$(($RANDOM % 2 + 1))m"
        tr -c "[:print:]" " " </dev/urandom | dd count=1 bs=50 2>/dev/null
    done)'

##
# Cool "The Matrix" type screens.
#
# @link @todo
#
alias matrix3='tr -c "[:digit:]" " " </dev/urandom |
    dd cbs=$(tput cols) conv=lcase,unblock |
    GREP_COLOR="1;32" grep --color "[^ ]"'
