#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

readonly REPOSITORY="${1?Repository not specified}"
readonly DESTINATION="${HOME}/workspace/$(sed --regexp-extended 's#\.git$##; s#^([a-z+]+://)?([^@]+@)?([^/:]+)[:/](.+)$#\3/\4#' <<< "${REPOSITORY}")"

if test -d "${DESTINATION}"; then
  echo "Repository ${REPOSITORY} has already been cloned to ${DESTINATION}" >&2
  exit 1
fi

# Create a bare clone of the repository.
git clone --bare "${REPOSITORY}" "${DESTINATION}/.git"
git -C "${DESTINATION}" config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
git -C "${DESTINATION}" fetch origin

# Set `refs/remotes/origin/HEAD` to match the remote's default branch.
git -C "${DESTINATION}" remote set-head origin --auto

# Create a worktree tracking the default branch.
readonly DEFAULT_BRANCH=$(git -C "${DESTINATION}" symbolic-ref --short refs/remotes/origin/HEAD | sed 's#^origin/##')
git -C "${DESTINATION}" worktree add "${DEFAULT_BRANCH}"
