#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

readonly REPOSITORY="${1?Repository not specified}"
readonly DESTINATION="${HOME}/workspace/$(sed --regexp-extended 's|\.git$||; s|^([a-z+]+://)?([^@]+@)?([^/:]+)[:/](.+)$|\3/\4|' <<< "${REPOSITORY}")"

if test -d "${DESTINATION}"; then
  echo "Repository ${REPOSITORY} has already been cloned to ${DESTINATION}" >&2
  exit 1
fi

git clone "${REPOSITORY}" "${DESTINATION}"
