# If not running interactively, don't do anything.
# See https://unix.stackexchange.com/a/257613.
if [[ $- != *i* ]]; then
  return
fi

includex "config/**.sh"
includex "config/**.bash"
includex "functions/**.sh"
includex "environment/**.sh"
includex "completion/**.sh"
includex "completion/**.bash"
