# If not running interactively, don't do anything.
case $- in
  *i*) ;;
    *) return;;
esac

includex "config/**.sh"
includex "config/**.bash"
includex "functions/**.sh"
includex "environment/**.sh"
includex "completion/**.sh"
includex "completion/**.bash"
