#!/bin/sh

##
# Prints terminal codes for shell colors.
#
# @param [String] Terminal code keyword (usually a colour).
#
# @link http://github.com/fnichol/bashrc/blob/master/bashrc
# @link http://github.com/wayneeseguin/rvm/blob/master/scripts/color
#
colorize() {
    local capname=setaf # foreground

    case $1 in
        # Emphasized (bolded) colors.
        b-* | bold-* | e-* | emph-*)
            tput bold
            ;;

        # Underlined colors.
        u-* | underline-*)
            set smul
            unset rmul
            ;;

        # Background colours.
        bg-* | background-*)
            capname=setab # background
            ;;
    esac

    case $1 in
        # regular colours
        black   | *-black  ) tput $capname 0 ;;
        red     | *-red    ) tput $capname 1 ;;
        green   | *-green  ) tput $capname 2 ;;
        yellow  | *-yellow ) tput $capname 3 ;;
        blue    | *-blue   ) tput $capname 4 ;;
        magenta | *-magenta) tput $capname 5 ;;
        cyan    | *-cyan   ) tput $capname 6 ;;
        white   | *-white  ) tput $capname 7 ;;

        # Defaults
        default | *-default) tput $capname 9 ;;
        none)                tput sgr0       ;;

        *)
            tput sgr0
            return 1
            ;;
    esac
    return 0
}
