#!/bin/bash

##
# Count code lines in the current directory.
#
# @param [List] The file extension(s) to count.
# @link @todo
#
loc() {
    local total=0
    local ext
    local lines

    for ext in $@; do
        if [ $(echo $ext | cut -c1-1) != '.' ]; then
            ext=".$ext"
        fi
        lines=$(find . -type f -name "*$ext" | xargs cat | wc -l)
        lines=${lines// /}
        total=$(($total + $lines))
        echo "Lines of code for $(colorize bold-green)$ext$(colorize-none): $(colorize cyan)$lines$(colorize none)"
    done
    echo "Total lines of code: $(colorize bold-yellow)$total$(colorize none)"
    return 0
}
