#!/bin/sh

##
# Creates the directory if it doesn't exist, and changes into it.
#
# @param [String] The path of the new directory.
#
mcd() {
    if [ -z $1 ]; then
        echo "usage: mcd <path>" >&2
        return 1
    fi

    if command -v pushd >/dev/null; then
        local cd_cmd=$(command -v pushd)
    else
        local cd_cmd=$(which cd)
    fi

    (mkdir -p $1 && $cd_cmd $1) >/dev/null
}

##
# Calculates a truncated `pwd`. Overriding of the truncation length can be done
# by setting "PROMPT_LEN".
#
# @link https://gist.github.com/548242
#
short_pwd() {
    local pwd_length=${PROMPT_LEN-35}
    local cur_pwd=$(echo $(pwd) | sed -e "s,^$HOME,~,")

    if [ $(echo -n $cur_pwd | wc -c | tr -d ' ') -gt $pwd_length ]; then
        echo "...$(echo $cur_pwd | sed -e "s/.*\(.\{$pwd_length\}\)/\1/")"
    else
        echo $cur_pwd
    fi
    return 0
}
