#!/bin/sh

##
# Checks whether a website is down for you, or everybody.
#
# @param [String] The URL.
#
down4me() {
    curl -s "http://www.downforeveryoneorjustme.com/$1" | sed '/just you/!d;s/<[^>]*>//g'
}

##
# Returns the primary IP address of the system.
#
# @link https://github.com/fnichol/bashrc/blob/master/bashrc
#
whats_my_primary_ip() {
    local def_gateway=
    local iface=
    local ip=

    case $(uname -s) in
        Darwin)
            iface=$(netstat -nr | grep ^default | grep -v 'link#' | awk '{print $6}')
            ip=$(ifconfig $iface | grep '^[[:space:]]*inet ' | awk '{print $2}')
            ;;
        OpenBSD)
            iface=$(netstat -nr | grep ^default | awk '{print $8}')
            ip=$(ifconfig $iface | grep '^[[:space:]]*inet ' | awk '{print $2}')
            ;;
        Linux)
            iface=$(netstat -nr | grep ^0\.0\.0\.0 | awk '{print $8}')
            ip=$(/sbin/ifconfig $iface | grep '^[[:space:]]*inet ' | awk '{print $2}' | awk -F':' '{print $2}')
            ;;
        SunOS)
            def_gateway=$(netstat -nr | grep ^default | awk '{print $2}')
            iface=$(route get $_def_gateway | \ grep '^[ ]*interface:' | awk '{print $2}')
            ip=$(ifconfig $iface |  awk '/^\t*inet / {print $2}')
            ;;
    esac

    if [ -z $ip ]; then
        echo "Could not determine primary IP address" >&2
        return 1
    else
        echo $ip
        return 0
    fi
}

##
# Determines the primary hostname of another domain name. Often used to resolve
# a website url (like "www.example.com") to a server hostname (like
# "webserver1.domainhosting.com").
#
# @params [String] Domainname to look up.
#
# @link https://github.com/fnichol/bashrc/blob/master/bashrc
#
hostfromdomain() {
    if [ -z $1 ]; then
        echo "usage: hostfromdomain <domainname>" >&2
        return 1
    else
        dig -x $(dig $1 +short) +short
    fi
}

##
# Returns the remote user's public SSH key on STDOUT. The host can optionally
# contain the username (like `jdoe@ssh.example.com') and a non-standard port
# number (like `ssh.example.com:666').
#
# @param [String] remote ssh host in for form of [<user>@]host[:<port>]
# @param [String] remote public key, using id_dsa.pub by default
#
mysshkey() {
    if [ -z "$1" ] ; then
        echo "Usage: mysshkey <ssh_host> [<pub_key>]" >&2
        return $RETURN_INVALID_CALL
    fi

    local host="$1" ; shift
    if [ -z "$1" ] ; then
        local key="id_dsa.pub"
    else
        local key="$1"
    fi
    shift

    if echo "$host" | egrep -q ':' ; then
        local ssh_cmd=$(echo $host | awk -F':' '{print \"ssh -p \" $2 \" \" $1}')
    else
        local ssh_cmd="ssh $host"
    fi

    $ssh_cmd "(cat .ssh/$key)"
}

##
# Places a given public ssh key on a remote host for key-based authentication.
# The host can optionally contain the username (like "jdoe@ssh.example.com")
# and a non-standard port number (like "ssh.example.com:666").
#
# @param [String] Remote ssh host in for form of [<user>@]host[:<port>].
# @param [String] Path to the public key.
#
authme() {
    if [ -z $1 ] ; then
        echo "Usage: authme <ssh_host> <public_key>" >&2
        return 1
    fi

    local host=$1
    if [ -z "$1" ] ; then
        local key="${HOME}/.ssh/id_dsa.pub"
    else
        local key="$1"
    fi
    shift

    [[ ! -f "$key" ]] && echo "SSH key: $key does not exist." && return 11

    if echo "$host" | egrep -q ':' ; then
        local ssh_cmd="$(echo $host | awk -F':' '{print \"ssh -p \" $2 \" \" $1}')"
    else
        local ssh_cmd="ssh $host"
    fi

    $ssh_cmd '(if [ ! -d "${HOME}/.ssh" ]; then \
        mkdir -m 0700 -p ${HOME}/.ssh; fi; \
        cat - >> .ssh/authorized_keys)' < $key
}
