#!/bin/sh

##
# The flavor of linux that we are using.
#
linux-flavor() {
    if [ -f /etc/redhat-release ]; then
        awk '{print $1}' /etc/redhat-release
    elif [ -f /etc/lsb-release ]; then
        head -n 1 /etc/lsb-release | awk -F= '{print $2}'
    else
        echo "Unable to determine Linux flavor" >&2
        return 1
    fi
    return 0
}
