#!/bin/sh

##
# Recursive source function.
#
# @param [String] The path of the file or directory to source.
#
source_r() {
    local file
    for file in $(find $1 -type f -readable 2>/dev/null); do
        source $file
    done
}
