---
name: 'Test'
on:
  pull_request: {}
  push: {}
  schedule:
    - cron: '0 0 * * 1'
jobs:
  bootstrap:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
        with:
          submodules: true
      - run: 'make test'
