---
name: 'Test'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * 1'
jobs:
  bootstrap:
    name: 'Bootstrap (ubuntu=${{ matrix.ubuntu_version }}, personal=${{ matrix.personal }}, work=${{ matrix.work }})'
    runs-on: 'ubuntu-latest'
    container: 'ubuntu:${{ matrix.ubuntu_version }}'
    env:
      DEBIAN_FRONTEND: 'noninteractive'
      GH_TOKEN: '${{ github.token }}'

    strategy:
      fail-fast: false
      matrix:
        personal:
          - false
          - true
        work:
          - false

        ubuntu_version:
          - '24.04'
          - '26.04'

    steps:
      - name: 'Install dependencies'
        run: |
          apt-get update --quiet
          apt-get install --no-install-recommends --quiet --yes curl git gpg software-properties-common sudo wget

      - name: 'Checkout repository'
        uses: 'actions/checkout@v7'
      - name: 'Setup Chezmoi'
        uses: './.github/actions/chezmoi'

      - name: 'Initialize Chezmoi'
        run: 'chezmoi init --promptBool "Enable personal profile=${{ matrix.personal }},Enable work profile=${{ matrix.work }}" .'
      - name: 'Run Chezmoi'
        run: 'chezmoi apply --keep-going'

  unit:
    name: 'Unit Tests (${{ matrix.directory }})'
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: '${{ matrix.directory }}'

    strategy:
      fail-fast: false
      matrix:
        include:
          - directory: 'dot_config/claude'
            provider: 'pnpm'

    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v6'

      - name: 'Setup pnpm'
        uses: 'pnpm/setup@v2.0.2'
        if: "matrix.provider == 'pnpm'"
        with:
          cache: true
          cache-dependency-path: '${{ matrix.directory }}/pnpm-lock.yaml'
          install: false
          package-json-file: '${{ matrix.directory }}/package.json'
      - name: 'Install dependencies'
        run: 'pnpm install --frozen-lockfile'
        if: "matrix.provider == 'pnpm'"
      - name: 'Run tests'
        run: 'pnpm run test'
        if: "matrix.provider == 'pnpm'"
