---
name: 'Test'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * 1'
jobs:
  bootstrap:
    runs-on: 'ubuntu-latest'
    container: 'ubuntu:${{ matrix.ubuntu_version }}'
    continue-on-error: '${{ matrix.experimental || false }}'
    env:
      DEBIAN_FRONTEND: 'noninteractive'
    strategy:
      fail-fast: false
      matrix:
        ubuntu_version:
          - '22.04'
          - '24.04'
          - 'rolling'
        include:
          - ubuntu_version: 'latest'
            experimental: true
    steps:
      - name: 'Install depdendencies'
        run: |
          apt-get update
          apt-get install --yes curl git gpg software-properties-common sudo wget

      - uses: 'actions/checkout@v4'
      - uses: './.github/actions/chezmoi'
      - run: 'chezmoi apply --verbose'
