---
name: 'Test'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * 1'
jobs:
  bootstrap:
    runs-on: 'ubuntu-latest'
    container: 'ubuntu:${{ matrix.ubuntu_version }}'
    continue-on-error: '${{ matrix.experimental || false }}'
    env:
      DEBIAN_FRONTEND: 'noninteractive'
    strategy:
      fail-fast: false
      matrix:
        personal:
          - false
          - true
        ubuntu_version:
          - '22.04'
          - '24.04'
          - 'rolling'
        include:
          - ubuntu_version: 'latest'
            experimental: true
    steps:
      - name: 'Install depdendencies'
        run: |
          apt-get update
          apt-get install --yes curl git gpg software-properties-common sudo wget

      - name: 'Checkout repository'
        uses: 'actions/checkout@v4'
      - run: |
          mkdir --parents $HOME/.config/chezmoi
          yq --null-input --prettyPrint '.data = ${{ toJSON(matrix) }}' > $HOME/.config/chezmoi/chezmoi.yaml
      - run: 'chezmoi data'

      - name: 'Setup Chezmoi'
        uses: './.github/actions/chezmoi'
      - name: 'Run Chezmoi'
        run: 'chezmoi apply --keep-going'
