---
name: 'Test'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * 1'
jobs:
  bootstrap:
    name: 'Bootstrap (ubuntu=${{ matrix.ubuntu_version }}, personal=${{ matrix.personal }}, work=${{ matrix.work }})'
    runs-on: 'ubuntu-latest'
    continue-on-error: "${{ matrix.ubuntu_version == 'rolling' }}"
    container: 'ubuntu:${{ matrix.ubuntu_version }}'
    env:
      DEBIAN_FRONTEND: 'noninteractive'
      GH_TOKEN: '${{ github.token }}'

    strategy:
      fail-fast: false
      matrix:
        personal:
          - false
          - true
        work:
          - false

        ubuntu_version:
          - '24.04'
          - 'latest'
          - 'rolling'

    steps:
      - name: 'Install depdendencies'
        run: |
          apt-get update
          apt-get install --yes curl git gpg software-properties-common sudo wget

      - name: 'Checkout repository'
        uses: 'actions/checkout@v4'
      - name: 'Setup Chezmoi'
        uses: './.github/actions/chezmoi'

      - name: 'Initialize Chezmoi'
        run: 'chezmoi init --promptBool "Enable personal profile=${{ matrix.personal }},Enable work profile=${{ matrix.work }}" .'
      - name: 'Run Chezmoi'
        run: 'chezmoi apply --keep-going'
