---
name: 'Test'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * 1'
jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - run: 'env'
      - run: 'env'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  bootstrap:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: './.github/actions/chezmoi'
      - run: 'chezmoi apply --verbose'
