apiVersion: v1
generated: "2020-02-06T07:52:33.023685838+11:00"
repositories:
- caFile: ""
  certFile: ""
  keyFile: ""
  name: stable
  password: ""
  url: https://kubernetes-charts.storage.googleapis.com
  username: ""
